const posts = [
  {
    _id: 0,
    name: 'Tesla',
    title: 'NFT Artist and Designer',
    category: ['NFT ARTIST', 'NFT DESIGNER', 'BLENDER'],
    type: ['Contract', 'Worldwide', '20% from Profit'],
    logo: 'https://benheine.com/wp-content/uploads/2021/06/Image-3-NFT-Crypto-Art-Market-Art-News-Blog-1024x683.jpg',
    roleDescriptions:
      'As a member of the Autopilot AI Tooling team you will design and implement a diverse set of tools that power our machine learning workflows. You will work closely with some of the best, world-class AI researchers and machine learning experts towards Tesla’s goal of a self-driving future. The AI Tooling team is a central part of Autopilot AI. The systems you build will have a large impact on the entire lifecycle of model development. This includes data processing, data discovery, annotation, and visualization. This also includes tools that help us automate the entire workflows of training, validation, and productionization of our Autopilot neural networks. As an engineer on the AI Tooling team, you bring top-notch software engineering skills and can contribute to our tooling systems immediately. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. That can be learned on the job as you work with our machine learning experts. A strong candidate for the AI Tooling team will either be an excellent software generalist, or someone who is exceptionally strong in either backend or frontend engineering.',
    resDescription:
      'Design and implement large-scale data processing pipelines that handle a diverse set of Autopilot related data such as images, sensor inputs, and human labels. Design and implement tools, tests,metrics, and dashboards to accelerate the development cycle of our model training. Work closely with frontend engineers to seamlessly integrate with backend systems. Work closely with AI researchers to support evolving research projects and implement new production features.',
    requirements:
      'BS/MS in Computer Science or related field, or equivalent industry experience. Strong knowledge of at least one programming language related to data engineering, such as Python or Scala is required. Experience with scientific computing libraries such as numpy, pandas, or scikit-learn is a plus. Experience with big data systems such as Spark, Hadoop/MapReduce is a plus. Experience with cloud computing such AWS EC2/S3/RDS is a plus. Experience with ElasticSearch or other scalable search systems is a plus. Experience with real-time data processing is a plus. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. Tesla participates in the E-Verify Program Tesla is an Equal Opportunity / Affirmative Action employer committed to diversity in the workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, age, national origin, disability, protected veteran status, gender identity or any other factor protected by applicable federal, state or local laws. Tesla is also committed to working with and providing reasonable accommodations to individuals with disabilities. Please let your recruiter know if you need an accommodation at any point during the interview process. Be sure to mention the words DICE DISEASE BOOST when applying to show you read the job post completely. This is a beta feature to avoid spam applicants.',
    location: 'Palo Alto, Austin or Remote',
  },
  {
    _id: 1,
    name: 'Tesla',
    title: 'NFT Artist and Designer',
    category: ['NFT ARTIST', 'NFT DESIGNER', 'BLENDER'],
    type: ['Contract', 'Worldwide', '20% from Profit'],
    logo: 'https://benheine.com/wp-content/uploads/2021/06/Image-3-NFT-Crypto-Art-Market-Art-News-Blog-1024x683.jpg',
    roleDescriptions:
      'As a member of the Autopilot AI Tooling team you will design and implement a diverse set of tools that power our machine learning workflows. You will work closely with some of the best, world-class AI researchers and machine learning experts towards Tesla’s goal of a self-driving future. The AI Tooling team is a central part of Autopilot AI. The systems you build will have a large impact on the entire lifecycle of model development. This includes data processing, data discovery, annotation, and visualization. This also includes tools that help us automate the entire workflows of training, validation, and productionization of our Autopilot neural networks. As an engineer on the AI Tooling team, you bring top-notch software engineering skills and can contribute to our tooling systems immediately. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. That can be learned on the job as you work with our machine learning experts. A strong candidate for the AI Tooling team will either be an excellent software generalist, or someone who is exceptionally strong in either backend or frontend engineering.',
    resDescription:
      'Design and implement large-scale data processing pipelines that handle a diverse set of Autopilot related data such as images, sensor inputs, and human labels. Design and implement tools, tests,metrics, and dashboards to accelerate the development cycle of our model training. Work closely with frontend engineers to seamlessly integrate with backend systems. Work closely with AI researchers to support evolving research projects and implement new production features.',
    requirements:
      'BS/MS in Computer Science or related field, or equivalent industry experience. Strong knowledge of at least one programming language related to data engineering, such as Python or Scala is required. Experience with scientific computing libraries such as numpy, pandas, or scikit-learn is a plus. Experience with big data systems such as Spark, Hadoop/MapReduce is a plus. Experience with cloud computing such AWS EC2/S3/RDS is a plus. Experience with ElasticSearch or other scalable search systems is a plus. Experience with real-time data processing is a plus. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. Tesla participates in the E-Verify Program Tesla is an Equal Opportunity / Affirmative Action employer committed to diversity in the workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, age, national origin, disability, protected veteran status, gender identity or any other factor protected by applicable federal, state or local laws. Tesla is also committed to working with and providing reasonable accommodations to individuals with disabilities. Please let your recruiter know if you need an accommodation at any point during the interview process. Be sure to mention the words DICE DISEASE BOOST when applying to show you read the job post completely. This is a beta feature to avoid spam applicants.',
    location: 'Palo Alto, Austin or Remote',
  },
  {
    _id: 2,
    name: 'Tesla',
    title: 'NFT Artist and Designer',
    category: ['NFT ARTIST', 'NFT DESIGNER', 'BLENDER'],
    type: ['Contract', 'Worldwide', '20% from Profit'],
    logo: 'https://benheine.com/wp-content/uploads/2021/06/Image-3-NFT-Crypto-Art-Market-Art-News-Blog-1024x683.jpg',
    roleDescriptions:
      'As a member of the Autopilot AI Tooling team you will design and implement a diverse set of tools that power our machine learning workflows. You will work closely with some of the best, world-class AI researchers and machine learning experts towards Tesla’s goal of a self-driving future. The AI Tooling team is a central part of Autopilot AI. The systems you build will have a large impact on the entire lifecycle of model development. This includes data processing, data discovery, annotation, and visualization. This also includes tools that help us automate the entire workflows of training, validation, and productionization of our Autopilot neural networks. As an engineer on the AI Tooling team, you bring top-notch software engineering skills and can contribute to our tooling systems immediately. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. That can be learned on the job as you work with our machine learning experts. A strong candidate for the AI Tooling team will either be an excellent software generalist, or someone who is exceptionally strong in either backend or frontend engineering.',
    resDescription:
      'Design and implement large-scale data processing pipelines that handle a diverse set of Autopilot related data such as images, sensor inputs, and human labels. Design and implement tools, tests,metrics, and dashboards to accelerate the development cycle of our model training. Work closely with frontend engineers to seamlessly integrate with backend systems. Work closely with AI researchers to support evolving research projects and implement new production features.',
    requirements:
      'BS/MS in Computer Science or related field, or equivalent industry experience. Strong knowledge of at least one programming language related to data engineering, such as Python or Scala is required. Experience with scientific computing libraries such as numpy, pandas, or scikit-learn is a plus. Experience with big data systems such as Spark, Hadoop/MapReduce is a plus. Experience with cloud computing such AWS EC2/S3/RDS is a plus. Experience with ElasticSearch or other scalable search systems is a plus. Experience with real-time data processing is a plus. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. Tesla participates in the E-Verify Program Tesla is an Equal Opportunity / Affirmative Action employer committed to diversity in the workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, age, national origin, disability, protected veteran status, gender identity or any other factor protected by applicable federal, state or local laws. Tesla is also committed to working with and providing reasonable accommodations to individuals with disabilities. Please let your recruiter know if you need an accommodation at any point during the interview process. Be sure to mention the words DICE DISEASE BOOST when applying to show you read the job post completely. This is a beta feature to avoid spam applicants.',
    location: 'Palo Alto, Austin or Remote',
  },
  {
    _id: 3,
    name: 'Tesla',
    title: 'NFT Artist and Designer',
    category: ['NFT ARTIST', 'NFT DESIGNER', 'BLENDER'],
    type: ['Contract', 'Worldwide', '20% from Profit'],
    logo: 'https://benheine.com/wp-content/uploads/2021/06/Image-3-NFT-Crypto-Art-Market-Art-News-Blog-1024x683.jpg',
    roleDescriptions:
      'As a member of the Autopilot AI Tooling team you will design and implement a diverse set of tools that power our machine learning workflows. You will work closely with some of the best, world-class AI researchers and machine learning experts towards Tesla’s goal of a self-driving future. The AI Tooling team is a central part of Autopilot AI. The systems you build will have a large impact on the entire lifecycle of model development. This includes data processing, data discovery, annotation, and visualization. This also includes tools that help us automate the entire workflows of training, validation, and productionization of our Autopilot neural networks. As an engineer on the AI Tooling team, you bring top-notch software engineering skills and can contribute to our tooling systems immediately. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. That can be learned on the job as you work with our machine learning experts. A strong candidate for the AI Tooling team will either be an excellent software generalist, or someone who is exceptionally strong in either backend or frontend engineering.',
    resDescription:
      'Design and implement large-scale data processing pipelines that handle a diverse set of Autopilot related data such as images, sensor inputs, and human labels. Design and implement tools, tests,metrics, and dashboards to accelerate the development cycle of our model training. Work closely with frontend engineers to seamlessly integrate with backend systems. Work closely with AI researchers to support evolving research projects and implement new production features.',
    requirements:
      'BS/MS in Computer Science or related field, or equivalent industry experience. Strong knowledge of at least one programming language related to data engineering, such as Python or Scala is required. Experience with scientific computing libraries such as numpy, pandas, or scikit-learn is a plus. Experience with big data systems such as Spark, Hadoop/MapReduce is a plus. Experience with cloud computing such AWS EC2/S3/RDS is a plus. Experience with ElasticSearch or other scalable search systems is a plus. Experience with real-time data processing is a plus. Knowledge of machine learning, computer vision, or neural networks is a plus but not required. Tesla participates in the E-Verify Program Tesla is an Equal Opportunity / Affirmative Action employer committed to diversity in the workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, age, national origin, disability, protected veteran status, gender identity or any other factor protected by applicable federal, state or local laws. Tesla is also committed to working with and providing reasonable accommodations to individuals with disabilities. Please let your recruiter know if you need an accommodation at any point during the interview process. Be sure to mention the words DICE DISEASE BOOST when applying to show you read the job post completely. This is a beta feature to avoid spam applicants.',
    location: 'Palo Alto, Austin or Remote',
  },
]

export default posts
